### ISSUE TITLE
Home-Client Testimonials: 'Client Testimonials' section is not implemented as stated in design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/NF-Engineering#13]
1. Background style is missing for left side
2. Give some gap between video container background image and background style as per design
3.  Gap observed between Video container background image and footer banner

![untitled-1-homne](https://cloud.githubusercontent.com/assets/13309730/13701548/ae7508ce-e7ae-11e5-97fa-630b732e7a69.png)

**Comment by mahender-sowedane** [comment]
Still not fixed properly
background style missing for large monitor resolutions like 1920px

![untitled-1-designbg](https://cloud.githubusercontent.com/assets/13309730/13869957/07a9adc2-ed00-11e5-9134-bad38194cc4f.png)

**Comment by ankittitan** [comment]
![bg-img](https://cloud.githubusercontent.com/assets/14210977/13975647/9de48f74-f0dd-11e5-8b42-c37294007cde.png)
