### ISSUE TITLE
W3C error on Projects page.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/NF-Engineering#3]
![2016-03-11_1605w3c](https://cloud.githubusercontent.com/assets/13309730/13699899/6d1dfec2-e7a3-11e5-8c1f-e295f9867036.png)

**Comment by ankittitan** [comment]
![errors](https://cloud.githubusercontent.com/assets/14210977/13818376/aa334314-ebbb-11e5-8491-02046c4b4046.png)
